# Generated by Django 2.0.6 on 2020-07-16 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200716_1819'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coursepricediscount',
            table='bz_course_price_dis',
        ),
    ]
