# Generated by Django 2.0.6 on 2020-07-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200716_1834'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coursepricediscount',
            table='bz_course_price_discount',
        ),
    ]
